---
title: "Projects"
---

#### Combinatorial Epigenetics

In this project, we combine chemical biology, biochemical, and proteomic approaches with cell biology and computational analyses to unravel how epigenetic effector molecules can read DNA and histone modification patterns and how they recognise different chromatin modification states. Our goal is to decipher the \"epigenetic code\" by identifying epigenetic reader molecules that can integrate information from multiple chromatin modifications and to understand how these factors operate at the molecular level both in healthy and pathological conditions. \
This project is done in close collaboration with Dr. Till Bartke from the Institute of Functional Epigenetics at Helmholtz Zentrum München. 

#### Decoding Chromatin States 

Lukauskas, S., Nguyen, N. V., Tvardovskiy, A., **Stadler, M.**, Faull, P., Flynn, H., Lindeboom, R. G. H., Barth, T. K., Ravnsborg, T., Hauck, S. M., Jensen, O. N., Vermeulen, M., Snijders, A. P., Müller, C. L., Schneider, R., DiMaggio, P. A., and Bartke, T.*Decoding Chromatin States by Proteomic Profiling of Modification-Dependent Nucleosome Readers.* Submitted for publication (2022).

#### RNF43 in colitis associated cancer

A Dietl, A Ralser, T Dregelies, W Sterlacci, M Vieth, X Li, **M Stadler**, \... *545: RNF43 in colitis associated cancer*. Gastroenterology 162 (7), S-129

#### Combinatorial drug effects on cell morphology 

In this project we collaborate with Erwin Kupczyk from the Environmental Health CenterAnalytical Biogeochemistry at Helmholtz Zentrum München to discover novel interaction effects between drugs and how they affect the morphology of single cells.

## More projects

#### Non-negative tensor factorization on COVID-19 data

*Ein Blick zurück auf die zweite Welle - wer war wann wo infiziert?*
Mara Stadler, Göran Kauermann, Christian L. Müller. CODAG Bericht Nr. 12 (available at: <https://www.covid19.statistik.uni-muenchen.de/pdfs/codag_bericht_12.pdf>)

#### Statistical modeling of dynamic eye-tracking experiments

Stadler, M., Doebler, P., Mertins, B. *et al.* *Statistical modeling of dynamic eye-tracking experiments: Relative importance of visual stimulus elements for gaze behavior in the multi-group case*. *Behav Res* **53**, 2650--2667 (2021). <https://doi.org/10.3758/s13428-021-01576-8>
			
		

	
